version: '3'

networks:
    lifecycle-network:

services:
    lifecycle-mysql:
        build: 
            context: ./docker/mysql      
            dockerfile: Dockerfile  
        tty: true
        cap_add:
            - SYS_NICE
        environment:
            - MYSQL_DATABASE=mydb
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
            - MYSQL_ROOT_PASSWORD=password
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3306:3306" 
        networks:
            - lifecycle-network    
        restart: unless-stopped                              
    lifecycle-php:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        tty: true
        volumes:
            - .:/app
            - ./logs/php.log:/var/log/fpm-php.www.log
        environment:
            - PHP_IDE_CONFIG=serverName=lifecycle.loc
            - XDEBUG_MODES=develop,debug
            - REMOTE_HOST=host.docker.internal
            - REMOTE_PORT=9003
            - IDE_KEY=docker
        extra_hosts:
            - host.docker.internal:host-gateway
        networks:
            - lifecycle-network 
        restart: always      
        depends_on:
            - lifecycle-mysql  
    lifecycle-nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        ports:
            - 8000:80
        volumes:
            - .:/app  
            - ./logs/nginx:/var/log/nginx/
        networks:
            - lifecycle-network  
        extra_hosts:
            - host.docker.internal:host-gateway    
        depends_on:
            - lifecycle-php
volumes:
    mysql_data:
